=== openwallet-foundation/credential-format-comparison-sig/viewer/src/schemas/Credential-Format.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/openwallet-foundation/credential-format-comparison-sig/main/viewer/src/schemas/Credential-Format.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Credential Format": {
      "type": "string",
      "description": "Unique identifier of the credential format."
    },
    "Implementation Support (e.g. Libraries) / Active Community": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Standardization (Body, Process)": {
      "$ref": "defs.json#/definitions/Standardization"
    },
    "Technology Readiness Level": {
      "$ref": "defs.json#/definitions/Technology-Readiness-Level"
    },
    "Encoding Scheme": {
      "type": "string",
      "description": "Data encoding on the storage layer which applies to this credential format."
    },
    "Rich Schemas/Semantic": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential format able to communicate data or annotations that supports the semantic understanding of the credential data?"
        }
      ]
    },
    "Crypto Agility": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential format capable to cover different cryptographic algorithms and achieve cryptographic agility, as demanded by regulations?"
        }
      ]
    },
    "Selective Disclosure": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential format capable of selective disclosure - presenting or revealing a subset of claims/attributes - without relying on architecture and protocol solutions like Just-in-Time issuance or a presentation transformation by a trusted third party?",
          "$comment": "Do we need to ask if kind of selective disclosure reveals more information like it should? Like using SD-JWT, the verifier can see that the value came from the same credential like in the past, but this is not the case for Anoncreds."
        }
      ]
    },
    "Predicates": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential Format able to produce general-purpose predicates, that means attestations without revealing the data, e.g. a proof to be over 18 without revealing the date of birth?"
        }
      ]
    },
    "Compatibility with Signing Algorithms": {
      "type": "string",
      "description": "What signing algorithms can the format be combined with?",
      "$comment": "TBD: https://github.com/openwallet-foundation/credential-format-comparison-sig/issues/44"
    },
    "Compatibility with Key Management Methods (Issuer)": {
      "type": "string",
      "description": "What key management methods can the credential format be combined with?",
      "$comment": "TBD: https://github.com/openwallet-foundation/credential-format-comparison-sig/issues/43"
    }
  },
  "required": ["$schema", "Credential Format"],
  "title": "CredentialFormat"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Format/CWT.json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Credential Format": "CWT",
  "Specification": "https://www.rfc-editor.org/rfc/rfc8392.html",
  "Standardization (Body, Process)": "IETF",
  "Technology Readiness Level": 8,
  "Encoding Scheme": "CBOR",
  "Crypto Agility": true,
  "Selective Disclosure": false,
  "Predicates": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Format/CESR-CESR-Proof.json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Credential Format": "CESR/CESR Proof",
  "Specification": "https://www.ietf.org/archive/id/draft-pfeairheller-cesr-proof-00.html",
  "Standardization (Body, Process)": "IETF (intention to go to Blockchain WG)",
  "Crypto Agility": true,
  "Selective Disclosure": true
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Format/ACDC-(KERI).json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Credential Format": "ACDC",
  "Specification": "https://trustoverip.github.io/tswg-acdc-specification/",
  "Standardization (Body, Process)": "",
  "Encoding Scheme": "CESR",
  "Rich Schemas/Semantic": false,
  "Crypto Agility": true,
  "Selective Disclosure": true,
  "Predicates": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Format/MDOC.json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Credential Format": "MDOC",
  "Implementation Support (e.g. Libraries) / Active Community": "Apple, Idemia, Thales, HID global, GET Group, Google, Panasonic, Spruce",
  "Specification": "ISO 18013-5",
  "Standardization (Body, Process)": "ISO",
  "Encoding Scheme": "CBOR",
  "Rich Schemas/Semantic": false,
  "Crypto Agility": true,
  "Selective Disclosure": {
    "Value": true,
    "Description": "salted hashes"
  },
  "Predicates": false,
  "Compatibility with Signing Algorithms": "ECDSA(NIST and Brainpool curves), EdDSA, RSA"
}
