=== openwallet-foundation/credential-format-comparison-sig/viewer/src/schemas/Signing-Algorithm.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/openwallet-foundation/credential-format-comparison-sig/tree/main/viewer/viewer/src/schemas/Signing-Algorithm.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "JSON Schema URI"
    },
    "Signing Algorithm": {
      "type": "string",
      "description": "Glossary"
    },
    "Implementation Support (e.g. Libraries) / Active Community": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Standardization (Body, Process)": {
      "$ref": "defs.json#/definitions/Standardization"
    },
    "Technology Readiness Level": {
      "$ref": "defs.json#/definitions/Technology-Readiness-Level"
    },
    "Recognition by government authorities (NIST, BSI, ...)": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the signing algorithm recognized in regulatory frameworks of leading government bodies?"
        }
      ]
    },
    "Performance": {
      "type": "string",
      "description": "How performant is the signing algorithm?"
    },
    "Hardware support": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the Signing Algorithm supported by common hardware-backed cryptographic implementations, such as Secure Elements, SecureEnclave, HSM, Strongbox, TEE, TPM"
        }
      ]
    },
    "Unlinkability/Uncorrelatability/Blind signatures possible": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the Signing Algorithm capable of creating a credential scheme, such that two verification processes can not be linked/correlated by colluding Verifiers/Relying Parties"
        }
      ]
    },
    "Security strength": {
      "type": "string",
      "description": "What level of security strength is common and standardized for this signing algorithm?"
    },
    "Post-quantum security": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the Signing Algorithm still secure if quantum computing achieves substantial computation power?"
        }
      ]
    }
  },
  "required": ["$schema", "Signing Algorithm"],
  "title": "SigningAlgorithm"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing-Algorithm/EdDSA.json
{
  "$schema": "./schema.json",
  "Signing Algorithm": "EdDSA",
  "Implementation Support (e.g. Libraries) / Active Community": "many mature implementations",
  "Recognition by government authorities (NIST, BSI, ...)": {
    "Value": true,
    "Description": "widely accepted, though still behind ECDSA"
  },
  "Performance": "high",
  "Hardware support": false,
  "Unlinkability/Uncorrelatability/Blind signatures possible": false,
  "Security strength": "257 / 384 / 512 bit",
  "Post-quantum security": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing-Algorithm/Schnorr.json
{
  "$schema": "./schema.json",
  "Signing Algorithm": "Schnorr",
  "Implementation Support (e.g. Libraries) / Active Community": "many mature implementations",
  "IPR Policy": "patents expired",
  "Specification": "different curves-different specs",
  "Standardization (Body, Process)": "different curves-different standards",
  "Technology Readiness Level": "TRL 9",
  "Recognition by government authorities (NIST, BSI, ...)": "NIST with Curve25519",
  "Performance": "high",
  "Hardware support": false,
  "Unlinkability/Uncorrelatability/Blind signatures possible": false,
  "Security strength": "tbd",
  "Post-quantum security": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing Algorithm/ECDSA.json
{
  "$schema": "./schema.json",
  "Signing Algorithm": "ECDSA",
  "Implementation Support (e.g. Libraries) / Active Community": "many mature implementations",
  "IPR Policy": "tbd",
  "Specification": "X9.62-2005",
  "Standardization (Body, Process)": "ANSI",
  "Technology Readiness Level": "TRL 9",
  "Recognition by government authorities (NIST, BSI, ...)": true,
  "Performance": "tbd",
  "Hardware support": true,
  "Unlinkability/Uncorrelatability/Blind signatures possible": false,
  "Security strength": "256 / 384 / 512 bit",
  "Post-quantum security": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing-Algorithm/BBS+-with-public-key-binding.json
{
  "$schema": "../../schemas/Signing-Algorithm.json",
  "Signing Algorithm": "BBS+ with public key binding",
  "Implementation Support (e.g. Libraries) / Active Community": "https://github.com/mattrglobal/bbs-signatures",
  "Specification": "https://datatracker.ietf.org/doc/draft-looker-cfrg-bbs-signatures/",
  "Standardization (Body, Process)": "DIF (intention to transfer to IRTF CFRG)",
  "Recognition by government authorities (NIST, BSI, ...)": {
    "Value": false,
    "Description": "not acknowledged"
  },
  "Hardware support": false,
  "Unlinkability/Uncorrelatability/Blind signatures possible": false,
  "Security strength": "381 bit curve",
  "Post-quantum security": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing-Algorithm/CL.json
{
  "$schema": "./schema.json",
  "Signing Algorithm": "CL",
  "Implementation Support (e.g. Libraries) / Active Community": "Hyperledger Ursa, https://github.com/privacybydesign/gabi ",
  "IPR Policy": "tbd",
  "Specification": "CL-Signatures of there own do not have a formal specification, that is included in Anoncreds",
  "Standardization (Body, Process)": "none",
  "Technology Readiness Level": "some",
  "Recognition by government authorities (NIST, BSI, ...)": "not acknowledged (indendent crypto analysis published)",
  "Performance": "Ursa: up to 7 seconds for a validation and approximately 30 seconds for credential definition generation; IRMA (Yivi): both in less than a second",
  "Hardware support": false,
  "Unlinkability/Uncorrelatability/Blind signatures possible": true,
  "Security strength": "equivalent to RSA2048",
  "Post-quantum security": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing Algorithm/BBS+ with public key binding.json
{
  "$schema": "./schema.json",
  "Signing Algorithm": "BBS+ with public key binding",
  "Implementation Support (e.g. Libraries) / Active Community": "https://github.com/mattrglobal/bbs-signatures",
  "IPR Policy": "tbd",
  "Specification": "https://datatracker.ietf.org/doc/draft-looker-cfrg-bbs-signatures/",
  "Standardization (Body, Process)": "DIF (intention to transfer to IRTF CFRG)",
  "Technology Readiness Level": "tbd",
  "Recognition by government authorities (NIST, BSI, ...)": "not acknowledged",
  "Performance": "tbd",
  "Hardware support": false,
  "Unlinkability/Uncorrelatability/Blind signatures possible": false,
  "Security strength": "381 bit curve",
  "Post-quantum security": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing-Algorithm/RSA.json
{
  "$schema": "./schema.json",
  "Signing Algorithm": "RSA",
  "Implementation Support (e.g. Libraries) / Active Community": "many mature implementations",
  "Technology Readiness Level": "TRL 9",
  "Recognition by government authorities (NIST, BSI, ...)": "yes, but support is fading",
  "Hardware support": true,
  "Unlinkability/Uncorrelatability/Blind signatures possible": false,
  "Security strength": "2048 / 3072 / 4096 (scales bad)",
  "Post-quantum security": false
}

=== openwallet-foundation/credential-format-comparison-sig/data/Signing-Algorithm/BoundBBS+.json
{
  "$schema": "./schema.json",
  "Signing Algorithm": "BoundBBS+",
  "IPR Policy": "barely",
  "Standardization (Body, Process)": "DIF (intention to transfer to IRTF CFRG)",
  "Recognition by government authorities (NIST, BSI, ...)": "not acknowledged",
  "Hardware support": false,
  "Unlinkability/Uncorrelatability/Blind signatures possible": true,
  "Post-quantum security": false
}
