=== openwallet-foundation/credential-format-comparison-sig/viewer/src/schemas/Trust-Management.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/openwallet-foundation/credential-format-comparison-sig/tree/main/viewer/viewer/src/schemas/Trust-Management.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "JSON Schema URI"
    },
    "Trust Management": {
      "type": "string",
      "description": "Glossary"
    },
    "Implementation Support (e.g. Libraries) / Active Community": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Standardization (Body, Process)": {
      "$ref": "defs.json#/definitions/Standardization"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Description": {
      "type": "string",
      "description": "Explanation how this trust management approach works"
    }
  },
  "required": ["$schema", "Trust Management"],
  "title": "TrustManagement"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Trust-Management/OpenID-Connect-Federation.json
{
  "$schema": "./schema.json",
  "Trust Management": "OpenID Connect Federation",
  "Standardization (Body, Process)": "OpenID Foundation",
  "Specification": "https://openid.net/specs/openid-connect-federation-1_0.html",
  "Description": "Uses JWTs and REST APIs to represent trust chains and trust marks"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Trust Management/X.509 certificates.json
{
  "$schema": "./schema.json",
  "Trust Management": "X.509 certificates",
  "Implementation Support (e.g. Libraries) / Active Community": "broadly available",
  "IPR Policy": "tbd",
  "Standardization (Body, Process)": "tbd",
  "Specification": "tbd",
  "Description": "Trust is managed by way of attributes attested in the certificate (e.g. could be role of an issuer) in combination with trust chains. The ultimate entity in the chain is typically trust anchor recipients need to rely in. "
}

=== openwallet-foundation/credential-format-comparison-sig/data/Trust-Management/Trusted-Lists.json
{
  "$schema": "./schema.json",
  "Trust Management": "Trusted Lists",
  "Standardization (Body, Process)": "ETSi",
  "Specification": "https://www.etsi.org/deliver/etsi_ts/119600_119699/119612/02.02.01_60/ts_119612v020201p.pdf",
  "Description": "used by EU Trusted List (https://webgate.ec.europa.eu/tl-browser/)"
}
