=== openwallet-foundation/credential-format-comparison-sig/schemas/Credential-Profile.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Credential-Profile.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Name": {
      "type": "string",
      "description": "The name of the credential profile, as it is commonly called.  This is the name that should be used to refer to the credential profile in other documents and discussions"
    },
    "Credential Profile Description": {
      "type": "string",
      "description": "A brief description of the credential profile"
    },
    "Credential Format": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Credential-Format"
        },
        {
          "description": "The format of the credential."
        }
      ]
    },
    "Signing Algorithm": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Signing-Algorithm"
        },
        {
          "description": "The format of the signing algorithm."
        }
      ]
    },
    "Status Algorithm": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Status-Algorithm"
        },
        {
          "description": "The format of the status algorithm."
        }
      ]
    },
    "Key Management (Issuer)": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Key-Management"
        },
        {
          "description": "The format of the key management for the issuer."
        }
      ]
    },
    "Key Management (Holder)": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Key-Management"
        },
        {
          "description": "The format of the key management for the holder."
        }
      ]
    },
    "Issuance Protocol": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Issuance-Protocol"
        },
        {
          "description": "The format of issuance protocol."
        }
      ]
    },
    "Presentation Protocol": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Presentation-Protocol"
        },
        {
          "description": "The format of the presentation protocol."
        }
      ]
    },
    "Trust Management": {
      "allOf": [
        {
          "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Trust-Management"
        },
        {
          "description": "The format of the trust management."
        }
      ]
    },
    "Formal Specification": {
      "type": "string",
      "description": "A link to a formal specification of the credential profile."
    }
  },
  "required": [
    "$schema",
    "Credential Format",
    "Credential Profile Description",
    "Name",
    "Key Management (Holder)",
    "Key Management (Issuer)",
    "Signing Algorithm"
  ],
  "title": "CredentialProfile"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Profile/HAIP.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "HAIP",
  "Credential Profile Description": "OpenID4VC High Assurance Interoperability Profile with SD-JWT-VC",
  "Formal Specification": "https://vcstuff.github.io/oid4vc-haip-sd-jwt-vc/draft-oid4vc-haip-sd-jwt-vc.html#name-authors-addresses",
  "Credential Format": "SD-JWT-VC",
  "Signing Algorithm": "ECDSA",
  "Status Algorithm": "JWT/CWT status list",
  "Key Management (Issuer)": ".well-known/jwt-issuer",
  "Key Management (Holder)": "raw public keys (jwk)",
  "Issuance Protocol": "OpenID4VCI",
  "Presentation Protocol": "OpenID4VP"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Profile/AnonCreds-cardano.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "AnonCreds with cardano blockchain",
  "Credential Profile Description": "AnonCreds with cardano blockchain",
  "Credential Format": "AnonCred",
  "Signing Algorithm": "CL",
  "Key Management (Issuer)": "did:web",
  "Key Management (Holder)": "link secrets",
  "Trust Management": "Verifier knows Issuers",
  "Formal Specification": "https://github.com/roots-id/cardano-anoncreds/blob/main/cardano-anoncred-methods.md"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Profile/JWT-VC-Presentation-Profile-2.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "JWT VC Presentation Profile 2",
  "Credential Profile Description": "https://identity.foundation/jwt-vc-presentation-profile/",
  "Credential Format": "JWT-VC",
  "Signing Algorithm": "ECDSA",
  "Status Algorithm": "Status List 2021",
  "Key Management (Issuer)": "did:web",
  "Key Management (Holder)": "did:ion (long form)"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Credential-Profile/AnonCreds-cheqd.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "AnonCreds with did:cheqd",
  "Credential Profile Description": "AnonCreds with did:cheqd",
  "Credential Format": "AnonCred",
  "Signing Algorithm": "CL",
  "Status Algorithm": "Indy Revocation",
  "Key Management (Issuer)": "did:cheqd",
  "Key Management (Holder)": "link secrets",
  "Formal Specification": "https://docs.cheqd.io/identity/advanced/anoncreds"
}
