=== openwallet-foundation/credential-format-comparison-sig/schemas/Key-Management.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/openwallet-foundation/credential-format-comparison-sig/schemas/Key-Management.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "JSON Schema URI"
    },
    "Key Management": {
      "type": "string",
      "description": "Glossary"
    },
    "Implementation Support (e.g. Libraries) / Active Community": {
      "type": "string",
      "description": "How complex is the implementation? Which/How many useful software libraries available?"
    },
    "IPR Policy": {
      "type": "string",
      "description": "What is the policy regarding intellectual properties associated with this technology?"
    },
    "Specification": {
      "type": "string",
      "description": "Where is the key management specified?"
    },
    "Infrastructure for Key Resolution": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is there any infrastructure required to resolve keys and/or validate identifier to key binding"
        }
      ]
    },
    "Key Rotation": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Can the key referred to in a credential be replaced by another key?"
        }
      ]
    },
    "Key History": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is it possible to retain and obtain the history of keys related to a certain identifier?"
        }
      ]
    },
    "Party": {
      "type": "array",
      "items": {
        "enum": ["issuer", "holder"]
      },
      "description": "What party may uses this technique?"
    }
  },
  "required": ["$schema", "Key Management"],
  "title": "KeyManagement"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Key-Management/did:ion-(long-form).json
{
  "$schema": "../../schemas/Key-Management.json",
  "Key Management": "did:ion (long form)",
  "Implementation Support (e.g. Libraries) / Active Community": "https://github.com/decentralized-identity/ion",
  "Infrastructure for Key Resolution": false,
  "Key Rotation": false,
  "Key History": false,
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/credential-format-comparison-sig/data/Key-Management/KERI.json
{
  "$schema": "./schema.json",
  "Key Management": "KERI",
  "Implementation Support (e.g. Libraries) / Active Community": "https://weboftrust.github.io/did-keri/",
  "Infrastructure for Key Resolution": {
    "Value": true,
    "Description": "witness network"
  },
  "Key Rotation": true,
  "Key History": true,
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/credential-format-comparison-sig/data/Key-Management/did:keri.json
{
  "$schema": "./schema.json",
  "Key Management": "did:keri",
  "Implementation Support (e.g. Libraries) / Active Community": "https://weboftrust.github.io/did-keri/",
  "Infrastructure for Key Resolution": "witness network",
  "Key Rotation": true,
  "Key History": true,
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/credential-format-comparison-sig/data/Key-Management/did:key.json
{
  "$schema": "./schema.json",
  "Key Management": "did:key",
  "Implementation Support (e.g. Libraries) / Active Community": "https://w3c-ccg.github.io/did-method-key/",
  "Infrastructure for Key Resolution": "none",
  "Key Rotation": false,
  "Key History": false,
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/credential-format-comparison-sig/data/Key-Management/did:web.json
{
  "$schema": "../../viewer/src/schemas/Key-Management.json",
  "Key Management": "did:web",
  "Implementation Support (e.g. Libraries) / Active Community": "https://github.com/w3c-ccg/did-method-web",
  "Infrastructure for Key Resolution": {
    "Value": true,
    "Description": "web server"
  },
  "Key Rotation": true,
  "Key History": false,
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/credential-format-comparison-sig/data/Key-Management/raw-public-keys-(jwk).json
{
  "$schema": "./schema.json",
  "Key Management": "raw public keys (jwk)",
  "Implementation Support (e.g. Libraries) / Active Community": "https://www.rfc-editor.org/rfc/rfc7517",
  "IPR Policy": "https://trustee.ietf.org/documents/trust-legal-provisions/",
  "Specification": "https://www.rfc-editor.org/rfc/rfc7517",
  "Infrastructure for Key Resolution": "none",
  "Key Rotation": false,
  "Key History": "conditional (with OpenID Connect Federation Key History)",
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/credential-format-comparison-sig/data/Key-Management/did:ebsi.json
{
  "$schema": "./schema.json",
  "Key Management": "did:ebsi",
  "Implementation Support (e.g. Libraries) / Active Community": "https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIDOC/EBSI+DID+Method",
  "Infrastructure for Key Resolution": "dlt",
  "Key Rotation": true,
  "Key History": "yes(?)",
  "Party": ["issuer"]
}
