=== openwallet-foundation/credential-format-comparison-sig/schemas/Revocation-Algorithm.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/openwallet-foundation/credential-format-comparison-sig/schemas/Revocation-Algorithm.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "JSON Schema URI"
    },
    "Revocation Algorithm": {
      "type": "string",
      "description": "Glossary"
    },
    "Implementation Support (e.g. Libraries) / Active Community": {
      "type": "string",
      "description": "How complex is the implementation? Which/How many useful software libraries available?"
    },
    "IPR Policy": {
      "type": "string",
      "description": "What is the policy regarding intellectual properties associated with this technology?"
    },
    "Specification": {
      "type": "string",
      "description": "Where is the revocation mechanism specified?"
    },
    "Standardization (Body, Process)": {
      "type": "string",
      "description": "Under which Standardization Body and which standards track/status is the revocation algorithm standardized"
    },
    "Technology Readiness Level": {
      "type": "number",
      "description": "According to NASA-Scheme (http://www.artemisinnovation.com/images/TRL_White_Paper_2004-Edited.pdf)"
    },
    "Recognition by government authorities (NIST, BSI, ...)": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the revocation algorithm recognized in regulatory frameworks of leading government bodies?"
        }
      ]
    },
    "Category": {
      "type": "string",
      "description": "Algorithm that behind the implementation of the revocation (Bitlist = each credential has a position in the list. Deny-List: revoked credentials will be added on demand. Accumulator: cryptographic proof the holder presents to show that the credential is not revoked)"
    },
    "Performance": {
      "type": "string",
      "description": "How performant is the revocation mechanism (for issuer, holder and verifier)?"
    },
    "Observability": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Does the Verifier have the possibility to observe the revocation status beyond the presentation?"
        }
      ]
    },
    "Traceability": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Does the issuer have possibilities to trace the usage of his issued credentials through the revocation mechanism?"
        }
      ]
    },
    "Scalability": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "At what scale has the algorithm/technology been demonstrated to work? Are there any known issues?"
        }
      ]
    },
    "Offline Friendliness": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Does the revocation mechanism support an authentication if the holder is offline?"
        }
      ]
    }
  },
  "required": ["$schema", "Revocation Algorithm"],
  "title": "RevocationAlgorithm"
}

=== openwallet-foundation/credential-format-comparison-sig/data/Revocation-Algorithm/Status-List-2021.json
{
  "$schema": "./schema.json",
  "Revocation Algorithm": "Status List 2021",
  "Implementation Support (e.g. Libraries) / Active Community": "https://github.com/transmute-industries/verifiable-data/tree/main/packages/vc-status-rl-2020",
  "Specification": "https://w3c-ccg.github.io/vc-status-list-2021/",
  "Standardization (Body, Process)": "W3C",
  "Recognition by government authorities (NIST, BSI, ...)": false,
  "Category": "Bitstring",
  "Observability": true,
  "Traceability": {
    "Value": true,
    "Description": "potentially possible with malicious issuer by providing a revocation list with a single entry"
  }
}

=== openwallet-foundation/credential-format-comparison-sig/data/Revocation-Algorithm/JWT-CWT-status-list.json
{
  "$schema": "../../viewer/src/schemas/Revocation-Algorithm.json",
  "Revocation Algorithm": "JWT/CWT status list",
  "Implementation Support (e.g. Libraries) / Active Community": "phython reference implementation",
  "Specification": "https://datatracker.ietf.org/doc/draft-terbu-oauth-sd-jwt-vc/",
  "Standardization (Body, Process)": "IETF Individual",
  "Recognition by government authorities (NIST, BSI, ...)": false,
  "Category": "Bitstring",
  "Observability": true,
  "Traceability": {
    "Value": true,
    "Description": "potentially possible with malicious issuer by providing a revocation list with a single entry"
  }
}

=== openwallet-foundation/credential-format-comparison-sig/data/Revocation-Algorithm/Indy-Revocation.json
{
  "$schema": "./schema.json",
  "Revocation Algorithm": "Indy Revocation",
  "Implementation Support (e.g. Libraries) / Active Community": "Indy SDK",
  "Standardization (Body, Process)": "AnonCreds",
  "Recognition by government authorities (NIST, BSI, ...)": false,
  "Category": "Accumulator",
  "Observability": false,
  "Scalability": "limitations by accumulator size"
}
